/* PAGE: Sessions (sidebar item "Sessions")
   Session list, session detail tabs (Agents, Conversation, Timeline, Report). Sample sessions are in sessions-data.js.
   Sample sessions, agents and the new-session generator used across the app. */
const S = [
  {
    id: 32,
    title: "Fix negative total in apply_discount()",
    repo: "acme/shop",
    s: "ok",
    open: false,
    add: 12,
    del: 3,
    when: "2h ago",
    model: "sonnet",
    cost: 0.42,
    file: "billing/pricing.py",
    rm: ["    return price - price * pct / 100"],
    ad: ["    pct = max(0, min(pct, 100))", "    return price - price * pct / 100"],
    tests: [
      ["test_discount_over_100 (new)", "fail", "pass"],
      ["test_discount_basic", "pass", "pass"],
      ["Rest of suite (91)", "pass", "pass"],
    ],
    gates: [
      ["Compiles", 1],
      ["Imports resolve", 1],
      ["Calls resolve (2 checked)", 1],
      ["Target test passes", 1],
      ["No regressions (95/95)", 1],
    ],
    log: [
      "Indexed 212 files and 94 tests.",
      "Located billing/pricing.py::apply_discount, called from 3 places.",
      "Wrote a failing test that reproduces the bug.",
      "Patched the function and ran every gate.",
    ],
  },
  {
    id: 31,
    title: "Add pagination to the /users endpoint",
    repo: "acme/api",
    s: "ok",
    open: true,
    add: 48,
    del: 6,
    when: "yesterday",
    model: "opus",
    cost: 1.18,
    file: "api/users.py",
    rm: ["    return User.query.all()"],
    ad: [
      "    users = User.query.order_by(User.id).all()",
      "    return paginate(users, page, per_page)",
    ],
    tests: [
      ["test_users_pagination (new)", "fail", "pass"],
      ["test_users_list_default", "pass", "pass"],
      ["Rest of suite (58)", "pass", "pass"],
    ],
    gates: [
      ["Compiles", 1],
      ["Imports resolve", 1],
      ["Calls resolve: paginate_query rejected, paginate accepted", 1],
      ["Target test passes", 1],
      ["No regressions (62/62)", 1],
    ],
    log: [
      "Indexed 148 files and 61 tests.",
      "Located api/users.py::list_users and api/utils.py::paginate.",
      "Attempt 1 called utils.paginate_query(). It does not exist, so the guard rejected it.",
      "Attempt 2 used paginate() and passed every gate.",
    ],
  },
  {
    id: 30,
    title: "Replace parse_date() calls with parse_iso()",
    repo: "acme/etl",
    s: "bad",
    open: true,
    add: 0,
    del: 0,
    when: "2 days ago",
    model: "sonnet",
    cost: 0.77,
    file: "etl/loader.py",
    rm: ["    d = parse_date(row[0])"],
    ad: ["    d = dateutil.parse_strict(row[0])"],
    tests: [
      ["Target test", "fail", "not run"],
      ["Full suite", "pass", "not run"],
    ],
    gates: [
      ["Compiles", 1],
      ["Imports resolve", 1],
      ["Calls resolve: dateutil.parse_strict not found", 0],
      ["Target test passes", null],
      ["No regressions", null],
    ],
    log: [
      "Indexed 96 files.",
      "Patch used dateutil.parse_strict(), which is not in the installed package.",
      "Three repair attempts failed the call check, so the agent stopped and reported.",
    ],
  },
];
const AG = [
  ["Main", "Coordinates the task", "working"],
  ["Locator", "Finds files and functions", "completed"],
  ["Patcher", "Writes the diff", "completed"],
  ["Verifier", "Runs gates and tests", "idle"],
];
const gen = (t) => ({
  id: 33,
  title: t,
  repo: "acme/shop",
  s: "run",
  open: true,
  add: 0,
  del: 0,
  when: "just now",
  model: "sonnet",
  cost: 0.3,
  file: "app/module.py",
  rm: ["    # existing logic"],
  ad: ["    # patched logic"],
  tests: [
    ["Target test (new)", "fail", "pass"],
    ["Full suite (95)", "pass", "pass"],
  ],
  gates: [
    ["Compiles", 1],
    ["Imports resolve", 1],
    ["Calls resolve", 1],
    ["Target test passes", 1],
    ["No regressions (96/96)", 1],
  ],
  log: [
    "Indexed repository.",
    "Located relevant functions.",
    "Wrote a reproducing test.",
    "Patched and ran every gate.",
  ],
});
